[package]
name = "certification-server"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
rocket = "0.2.4"
rocket_codegen = "0.2.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
multipart = "0.11"

[dependencies.rocket_contrib]
version = "0.2.4"
default-features = false
features = ["handlebars_templates"]
